version: '3.8'

services:
  nestjs_app:
    build:
      context: .
      dockerfile: Dockerfile
    image: amarant1995/nestjs_app
    container_name: nestjs_app
    ports:
      - 3000:3000

    volumes:
      - ./:/app/src

volumes:
  nestjs_app:
